ALTER TABLE "Voucher"
ADD COLUMN IF NOT EXISTS "notifyAtStart" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "promoNotifiedAt" TIMESTAMP(3);

ALTER TABLE "ProductDiscount"
ADD COLUMN IF NOT EXISTS "notifyAtStart" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "promoNotifiedAt" TIMESTAMP(3);
