ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_PICKUP';

ALTER TABLE "Order"
  ADD COLUMN IF NOT EXISTS "orderType" TEXT NOT NULL DEFAULT 'DELIVERY',
  ADD COLUMN IF NOT EXISTS "shippingMethod" TEXT NOT NULL DEFAULT 'DELIVERY',
  ADD COLUMN IF NOT EXISTS "pickupStoreName" TEXT,
  ADD COLUMN IF NOT EXISTS "pickupStoreAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "pickupStoreLatitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pickupStoreLongitude" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "pickupHours" TEXT,
  ADD COLUMN IF NOT EXISTS "pickupCode" TEXT,
  ADD COLUMN IF NOT EXISTS "pickupQrCode" TEXT,
  ADD COLUMN IF NOT EXISTS "pickupStatus" TEXT,
  ADD COLUMN IF NOT EXISTS "readyForPickupAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "pickedUpAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "pickedUpByAdminId" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Order_pickupCode_key" ON "Order"("pickupCode");
CREATE INDEX IF NOT EXISTS "Order_orderType_idx" ON "Order"("orderType");
CREATE INDEX IF NOT EXISTS "Order_pickupStatus_idx" ON "Order"("pickupStatus");
