-- AlterTable
ALTER TABLE "FeedPost" ADD COLUMN IF NOT EXISTS "notifyOnPublish" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "FeedPost" ADD COLUMN IF NOT EXISTS "pushSegment" TEXT;
ALTER TABLE "FeedPost" ADD COLUMN IF NOT EXISTS "publishPushSentAt" TIMESTAMP(3);
